os: linux
language: node_js
node_js: "14"
env:
  - RELEASE_FILE=dist/jvig-*.AppImage

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

if: tag =~ /^v/

deploy:
  provider: releases
  file: $RELEASE_FILE
  api_key: $GITHUB_PUBLISH_RELEASE
  skip_cleanup: true
  on:
    tags: true
