language: node_js
node_js:
  - "16"

install:
  - npm install

script:
  - npm test

stages:
  - test
  - name: deploy
    if: tag IS PRESENT AND repo = MKuranowski/jvig

jobs:
  include:
  - os: linux
    language: node_js
    node_js: "16"
    stage: deploy
    env:
      - RELEASE_FILE=dist/jvig-*.AppImage

  - os: windows
    language: node_js
    node_js: "16"
    stage: deploy
    env:
      - RELEASE_FILE=dist/jvig-*-setup.exe
      - HOME=$LOCALAPPDATA
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_deploy: |
  if [ "$TRAVIS_OS_NAME" == "windows" ]; then
    npm run dist:win32
  else
    npm run dist
  fi

deploy:
  provider: releases
  file: $RELEASE_FILE
  file_glob: true
  api_key: $GITHUB_PUBLISH_RELEASE
  skip_cleanup: true
  on:
    tags: true
