jobs:
  include:
  - os: linux
    language: node_js
    node_js: "14"
    env:
      - RELEASE_FILE=dist/jvig-*.AppImage

  - os: windows
    language: node_js
    node_js: "14"
    env:
      - RELEASE_FILE=dist/jvig-*-setup.exe
      - HOME=$LOCALAPPDATA
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

if: tag =~ /^v/

before_deploy: |
  if [ "$TRAVIS_OS_NAME" == "windows" ]; then
    npm run dist:win32
  else
    npm run dist
  fi

deploy:
  provider: releases
  file: $RELEASE_FILE
  file_glob: true
  api_key: $GITHUB_PUBLISH_RELEASE
  skip_cleanup: true
  on:
    tags: true
