language: node_js
node_js:
  - "17"

stages:
  - test
  - name: deploy
    if: tag IS PRESENT AND repo = MKuranowski/jvig

jobs:
  include:
  - os: linux
    stage: test
    install: npm install
    script: npm test

  - os: linux
    language: node_js
    node_js: "17"
    stage: deploy
    install: npm install
    before_deploy: npm run dist
    deploy:
      provider: releases
      file: dist/jvig-*.AppImage
      file_glob: true
      api_key: $GITHUB_PUBLISH_RELEASE
      skip_cleanup: true
      on:
        tags: true

  - os: windows
    language: node_js
    node_js: "17"
    stage: deploy
    env:
      - HOME=$LOCALAPPDATA
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    before_deploy: npm run dist:win32
    deploy:
      provider: releases
      file: dist/jvig-*-setup.exe
      file_glob: true
      api_key: $GITHUB_PUBLISH_RELEASE
      skip_cleanup: true
      on:
        tags: true

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
