name: Jvig automatic checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -Ur requirements.dev.txt
    - name: Check code formatting (with black)
      run: black --check .
    - name: Ensure imports have proper ordering (with isort)
      run: isort --check .
    - name: Perform typechecking (with pyright)
      run: pyright
    - name: Test (with pytest)
      run: python -m pytest
